### ISSUE TITLE
URLの指定方法

### ISSUE THREAD

**Issue by yosukeaonuma** [nakagawa-takahiro/Assignment#1]
https://github.com/nakagawa-takahiro/Assignment/blob/fe4234a63fe4dd098bcf870d390d26b6f26175e1/fuel/app/views/message/index.php#L66
毎回 https://~~~ と書くのは面倒なので、[FuelPHPのUriクラス](http://fuelphp.jp/docs/1.7/classes/uri.html)というのを使うと良いと思う！
`Uri::create()`あたりが良いかな

**Comment by nakagawa-takahiro** [comment]
このように修正しました。

```url: '<?php echo Uri::create('chat/chat_post.json'); ?>',```
