### ISSUE TITLE
物理削除か、論理削除か

### ISSUE THREAD

**Issue by yosukeaonuma** [nakagawa-takahiro/Assignment#11]
https://github.com/nakagawa-takahiro/Assignment/blob/93ed46743ed172008c3f41de3a239e600f12da7e/fuel/app/classes/controller/chat.php#L65
知っている上で物理削除にしているのであれば恐縮だけど、
DBからの削除の方法としては物理削除と論理削除という方法がある！（詳しくはググろう）
完全にDBから削除してしまって良い場合は物理削除で問題ないけど、それ以外は基本論理削除にするのが無難なので、
一度どっちの方が良いか考えて見て欲しい！
ちなみにかんりくんの場合は論理削除するときは、deleted_at というカラムを用意して、そこに日付を入れることで削除したとみなす
という実装をとってる！

**Comment by nakagawa-takahiro** [comment]
物理削除したときにidに抜けが出てしまうのをどうしようか考えていて、deleteというカラム(1or0)を用意して判定しようと思っていました。
deleted_atでNull or 日付で判定する方がよさそうなので、その方法を取り入れたいと思います！

**Comment by nakagawa-takahiro** [comment]
論理削除に変更しました！

**Comment by yosukeaonuma** [comment]
いい感じ！
