### ISSUE TITLE
非同期処理にするために

### ISSUE THREAD

**Issue by yosukeaonuma** [nakagawa-takahiro/Assignment#5]
https://github.com/nakagawa-takahiro/Assignment/blob/5913d9d2081db799176dd26ae7eae22973289528/fuel/app/views/message/index.php#L34
今の動作っておそらく
送信ボタンクリック
⇨ `submitForm`
⇨ ajaxで`chat_post.json`
⇨`<form action="" method="post">`の動作で`public function action_index($loginUser)`にリダイレクト
⇨非同期っぽく見える
となっていて非同期にはなっていなそう！？
（動画のconsoleがリロードされてるの見て気づいた）
この行を`function submitForm(event){`としてすぐ下で`event.preventDefault();`とすると、
もともとのformの動きをしないようにできる！

**Comment by nakagawa-takahiro** [comment]
preventDeafault()でformの動きを止めると、ajaxでの成功や失敗のalertが表示されず、一瞬だけエラーが表示され(すぐ消えるのでエラー詳細が確認できない)、データベースへの登録もできていませんでした。
consoleにはおそらくUncaughtと表示されています。

また、localhost/chat/chat_postを開くと
Failed to load resource: the server responded with a status of 405 ()
というエラーが出ているんですけど、それと何か関係ありそうですか？
これは非同期っぽく見えるときにも出ていました。

**Comment by nakagawa-takahiro** [comment]
`function submitForm(){
event.preventDefault();`
とするとエラーがなくなり、コンソールの更新もされなくなりました！
ただ、送信したメッセージも画面に反映されなくなりました。
データベースへの登録はできています。

**Comment by nakagawa-takahiro** [comment]
おそらく、.done内のpushが機能していないので書き直してみます！
