### ISSUE TITLE
INSERTしたレコードの取得方法について

### ISSUE THREAD

**Issue by yosukeaonuma** [nakagawa-takahiro/Assignment#6]
https://github.com/nakagawa-takahiro/Assignment/blob/3190534f30e3a68978dff1784e024ecef7c9e3e9/fuel/app/classes/controller/chat.php#L20
ここからの処理ってINSERTしたmessagesの情報を返していると思うんだけど、もうちょい工夫できそう！

まずこの行でSELECTに使っている情報について、今は「降順にした一番新しいものをとってくる」にしているようだけど、
INSERTしたレコードのIDがわかればそのものズバリのレコードが取れるはず。
そこで、15行目のINSERT文だけど、FuelのINSERTやUPDATEにも返り値があって、今回の場合は返り値の配列の最初の要素にINSERTしたレコードのIDが入っている（はず）！
https://qiita.com/Quantum/items/f090fd9081d2d76581ed
なのでこの値を使えばほしいレコードが取れると思う！

そして22行目ではforeachしているけど、20行目で`->current();`とすると一個だけかつ連想配列じゃなくてただの配列でレコードが取れるようになるので、ほぼそのまま使える！
http://fuelphp.jp/docs/1.6/classes/database/usage.html

あとちなみにで、配列の宣言は`array()`のほかに`[]`でもいけるので、好みの方で！（自分は最近は、記述量が少ないから`[]`で書くようにしてる）

**Comment by nakagawa-takahiro** [comment]
まさにその部分についてissueを作ろうと思っていました！
たしかにレコードの取り方はもっと工夫できそうですね。
書き直します！

**Comment by nakagawa-takahiro** [comment]
$insert = DB::insert('messages')->set([
		'username' => "$username",
		'content' => "$message",
])->execute();

$data = DB::select()->from('messages')->where('id', $insert[0])
->execute()->current();

$id = $data['id'];
$username = $data['username'];
$content = $data['content'];
$posted_at = $data['posted_at'];

こんな感じで書き直しました！

**Comment by yosukeaonuma** [comment]
いいと思う！
