### ISSUE TITLE
CSRF対策について

### ISSUE THREAD

**Issue by yosukeaonuma** [nakagawa-takahiro/Assignment#7]
https://github.com/nakagawa-takahiro/Assignment/blob/3190534f30e3a68978dff1784e024ecef7c9e3e9/fuel/app/classes/controller/chat.php#L10
ちょっとずつセキュリティ的な面も、気づいたことから言っていこうと思うんだけど、今回はCSRFというものへの対策について！
（詳しくは調べてみて）
メジャーな脆弱性なので言語・フレームワークで対策できることが多くて、Fuelも対策を用意している！http://fuelphp.jp/docs/1.7/general/security.html#csrf
使い方は簡単で、view側のheaderなどで`<?php echo \Security::js_fetch_token(); ?>`と書き（準備）、
ajaxで渡すdataの中に`'cc_token':fuel_csrf_token()`を追加し（サーバーへトークンを送信）、
受け取ったこのメソッドの中で

>  if (!\Security::check_token()) :// ここ
      $res = array(
        'error' => 'セッションが切れている可能性があります。'
      );
      return $this->response($res);
    endif;

のようにする（トークンが正しいかチェック）！

かんりくんでは、情報をSELECTするような処理だけのメソッドではこの対策をしない場合も多いけど、INSERTやUPDATEを含む非同期で動くメソッドでは基本入れるようにしている！

**Comment by nakagawa-takahiro** [comment]
`<?php echo \Security::js_fetch_token(); ?>`
も追加しないとfuel_csrf_token()が呼べないみたいなので追加しました。

**Comment by nakagawa-takahiro** [comment]
`$cc = Input::post('cc_token');`
`if (!\Security::check_token($cc)) :`
           ` $res = array(`
           ` 'error' => 'セッションが切れている可能性があります。'`
`);`

改行されていて見にくいですが、トークンを直接入れればエラーは出なくなりました。
以前共有いただいたコード(Rest_controller)ではcheck_tokenの引数には何も入っていないみたいですが、どこが違うのかわからないです。

**Comment by yosukeaonuma** [comment]
Coreのコード読んでみたんだけど、
`config/config.php`
の`'csrf_token_key'`ってところで設定しているっぽい？
`'csrf_token_key'   => 'cc_token',`とすれば引数なしでもいけるかな？

**Comment by nakagawa-takahiro** [comment]
その通りでした！
さすがですね、ありがとうございます！
